program AmvSys; //SystemID=5




uses
  RadForms in 'RadForms.pas' {RadForm},
  UUserMsg in 'UUserMsg.pas',
  define in 'define.pas',
  DRWPNEL in 'DRWPNEL.PAS',
  Fard in 'Fard.pas',
  fmAccComiss in 'fmAccComiss.pas' {AccidComiss},
  fmAccComissApp in 'fmAccComissApp.pas' {AccidComissApp},
  fmAccComissCfm in 'fmAccComissCfm.pas' {AccidComissCfm},
  fmActiveUser in 'fmActiveUser.pas' {ActiveUser},
  fmAnimal in 'fmAnimal.pas' {Animal},
  fmanimaldet in 'fmanimaldet.pas' {animaldet},
  fmBillItemReq in 'fmBillItemReq.pas' {BillItemReq},
  fmBillMov in 'fmBillMov.pas' {Billmovable},
  fmBillMovCfm in 'fmBillMovCfm.pas' {BillmovableCfm},
  fmBillReturn in 'fmBillReturn.pas' {BillReturn},
  fmBillReturnCfm in 'fmBillReturnCfm.pas' {BillReturnCfm},
  fmBills in 'fmBills.pas' {Bills},
  fmBillStorCfm in 'fmBillStorCfm.pas' {BillStorCfm},
  fmBillUser in 'fmBillUser.pas' {BillUser},
  fmbook in 'fmbook.pas' {book},
  fmbookdet in 'fmbookdet.pas' {bookdet},
  fmDefineOrg in 'fmDefineOrg.pas' {DefineOrg},
  fmdelGoods in 'fmdelGoods.pas' {DelGoods},
  fmdesc in 'fmdesc.pas' {desc},
  fmDetailGroups in 'fmDetailGroups.pas' {DetailGroups},
  fmElam in 'fmElam.pas' {Elam},
  fmElamDel in 'fmElamDel.pas' {ElamDel},
  fmexitlic in 'fmexitlic.pas' {ExitLic},
  fmExitLicCfm in 'fmExitLicCfm.pas' {ExitLicCfm},
  fmfilm in 'fmfilm.pas' {film},
  fmfilmdet in 'fmfilmdet.pas' {filmdet},
  fmgoodinfo in 'fmgoodinfo.pas' {Goodinfo},
  fmgoods in 'fmgoods.pas' {goods},
  fmgoodsdet in 'fmgoodsdet.pas' {goodsdet},
  fmGoodsRec in 'fmGoodsRec.pas' {GoodsRec},
  fmGoodsRecOrderNo in 'fmGoodsRecOrderNo.pas' {GoodsRecOrderNo},
  fmInBills in 'fmInBills.pas' {InBills},
  fmincons in 'fmincons.pas' {incons},
  fminconsdet in 'fminconsdet.pas' {inconsdet},
  fmInGoodsRec in 'fmInGoodsRec.pas' {InGoodsRec},
  fmInItemOrderRequest in 'fmInItemOrderRequest.pas' {InItemOrderRequest},
  fmInNewBill in 'fmInNewBill.pas' {InNewBill},
  fmInNewBills in 'fmInNewBills.pas' {InNewBills},
  fmInputReqItem in 'fmInputReqItem.pas' {InputReqItem},
  fmInRecItem in 'fmInRecItem.pas' {InRecItem},
  fmInUseTrans in 'fmInUseTrans.pas' {InUseTrans},
  fmitem in 'fmitem.pas' {Item},
  fmItemOrderRequest in 'fmItemOrderRequest.pas' {ItemOrderRequest},
  fmItemReqConfirm in 'fmItemReqConfirm.pas' {ItemReqConfirm},
  fmItemRequest in 'fmItemRequest.pas' {ItemReq},
  fmItemRequestInput in 'fmItemRequestInput.pas' {ItemReqInput},
  fmItemRequestList in 'fmItemRequestList.pas' {ItemRequestList},
  fmItemReqVerify in 'fmItemReqVerify.pas' {ItemReqVerify},
  fmItemViewer in 'fmItemViewer.pas' {ItemVeiwer},
  fmlens in 'fmlens.pas' {lens},
  fmlensdet in 'fmlensdet.pas' {lensdet},
  fmLine in 'fmLine.pas' {Line},
  fmListAssetRoom in 'fmListAssetRoom.pas' {ListAssetRoom},
  fmloc in 'fmloc.pas' {Loc},
  fmlocspc in 'fmlocspc.pas' {GeoLoc},
  fmLogView in 'fmLogView.pas' {LogView},
  fmMachin in 'fmMachin.pas' {machin},
  fmMachindet in 'fmMachindet.pas' {machindet},
  fmMasterGroups in 'fmMasterGroups.pas' {MasterGroups},
  fmmedical in 'fmmedical.pas' {medical},
  fmmedicaldet in 'fmmedicaldet.pas' {medicaldet},
  fmMgdet in 'fmMgdet.pas' {mgdet},
  fmMoveable in 'fmMoveable.pas' {moveable},
  fmmusdet in 'fmmusdet.pas' {musdet},
  fmmuseum in 'fmmuseum.pas' {museum},
  fmMuseumSpecRep in 'fmMuseumSpecRep.pas' {reSpcMuseum},
  fmNewBills in 'fmNewBills.pas' {NewBills},
  fmnmgdet in 'fmnmgdet.pas' {nmgdet},
  fmnonmgood in 'fmnonmgood.pas' {nonmgood},
  fmOrdReqItem in 'fmOrdReqItem.pas' {OrdReqItem},
  fmParameters in 'fmParameters.pas' {ParametersFrm},
  fmreAnimal in 'fmreAnimal.pas' {reSpecAnimal},
  fmreBooks in 'fmreBooks.pas' {reSpecBooks},
  fmreDbtRepMoon in 'fmreDbtRepMoon.pas' {reMachin},
  fmreExitLic in 'fmreExitLic.pas' {reexitlic},
  fmreGetAntiq in 'fmreGetAntiq.pas' {reSpcMachin1},
  fmreIncon in 'fmreIncon.pas' {reStampSpec1},
  fmreLab in 'fmreLab.pas' {reSpecLab},
  fmreLens in 'fmreLens.pas' {reSpecLens},
  fmreListAssetPresent in 'fmreListAssetPresent.pas' {reListAssetPresent},
  fmreListAssetUnreasonable in 'fmreListAssetUnreasonable.pas' {reListAssetUnreasonable},
  fmreListSmallAsset in 'fmreListSmallAsset.pas' {reListSmallAsset},
  fmreListStateAssetUnreasonable in 'fmreListStateAssetUnreasonable.pas' {reListStateAssetUnreasonable},
  fmreMachinery in 'fmreMachinery.pas' {reSpecMachinery},
  fmremovstate in 'fmremovstate.pas' {reMovstate},
  fmRepClass in 'fmRepClass.pas' {RepClass},
  fmrepitem in 'fmrepitem.pas' {repItem},
  fmrepItemRepair in 'fmrepItemRepair.pas' {repItemRepair},
  fmrepItemReq in 'fmrepItemReq.pas' {repItemReq},
  fmrepItemRequest in 'fmrepItemRequest.pas' {repItemRequest},
  fmRepItems in 'fmRepItems.pas' {repItems},
  fmrepRec in 'fmrepRec.pas' {repRec},
  fmrepRecItem in 'fmrepRecItem.pas' {repRecItem},
  fmRePropAssetMan in 'fmRePropAssetMan.pas' {rePropAssetMan},
  fmRepSrtAll in 'fmRepSrtAll.pas' {reSrtAll},
  fmreRide in 'fmreRide.pas' {reSpecRide},
  fmreSpcAntiq in 'fmreSpcAntiq.pas' {reSpcAntiq},
  fmreSpcMachin in 'fmreSpcMachin.pas' {reSpcMachin},
  fmReSpecAll in 'fmReSpecAll.pas' {reSpecAll},
  fmreSpecInco in 'fmreSpecInco.PAS' {reSpecIncon},
  fmresrtAntique in 'fmresrtAntique.pas' {reSrtantique},
  fmreSrtMuseum in 'fmreSrtMuseum.pas' {reSrtMuseum},
  fmreSrtRide in 'fmreSrtRide.pas' {reSrtRide},
  fmreSrtStamp in 'fmreSrtStamp.pas' {reSrtStamp},
  fmreStampSpec in 'fmreStampSpec.pas' {reStampSpec},
  fmreTaxidermy in 'fmreTaxidermy.pas' {reSpecTaxidermy},
  fmreTextile in 'fmreTextile.pas' {reSpecTextile},
  fmreUnused in 'fmreUnused.pas' {reunused},
  fmSaleCom in 'fmSaleCom.pas' {SaleCom},
  fmSaleComCfm in 'fmSaleComCfm.pas' {SaleComCfm},
  fmSelAvailableGoods in 'fmSelAvailableGoods.pas' {SelAvailableGoods},
  fmSetBillUserName in 'fmSetBillUserName.pas' {SetBillUserName},
  fmShowMal in 'fmShowMal.pas' {ShowMal},
  fmShowMG in 'fmShowMG.pas' {ShowMvGood},
  fmShowNMGood in 'fmShowNMGood.pas' {ShowNonMGood},
  fmspec in 'fmspec.pas' {specific},
  fmSrtAnimal in 'fmSrtAnimal.pas' {reSrtAnimal},
  fmSrtBooks in 'fmSrtBooks.pas' {reSrtBooks},
  fmSrtDiskette in 'fmSrtDiskette.pas' {reSrtDiskette},
  fmSrtincon in 'fmSrtincon.pas' {reSrtIncon},
  fmSrtLab in 'fmSrtLab.pas' {reSrtLab},
  fmSrtLens in 'fmSrtLens.pas' {reSrtLens},
  fmSrtMachinery in 'fmSrtMachinery.pas' {reSrtMachinery},
  fmSrtTaxidermy in 'fmSrtTaxidermy.pas' {reSrtTaxidermy},
  fmSrtTextile in 'fmSrtTextile.pas' {reSrtTextile},
  fmStamp in 'fmStamp.pas' {stamp},
  fmstampdet in 'fmstampdet.pas' {stampdet},
  fmtaxidermy in 'fmtaxidermy.pas' {taxidermy},
  fmtaxidermydet in 'fmtaxidermydet.pas' {taxidermydet},
  fmtextile in 'fmtextile.pas' {textile},
  fmtextiledet in 'fmtextiledet.pas' {textiledet},
  fmTimeZone in 'fmTimeZone.pas' {timeZone},
  fmTransOrderNo in 'fmTransOrderNo.pas' {TransOrderNo},
  fmtrasport in 'fmtrasport.pas' {Transport},
  fmtrdet in 'fmtrdet.pas' {trdet},
  fmTreeItem in 'fmTreeItem.pas' {TreeItem},
  fmTrRec in 'fmTrRec.pas' {TrRec},
  fmTrrecApp in 'fmTrrecApp.pas' {TrRecApp},
  fmTrrecCfm in 'fmTrrecCfm.pas' {TrRecCfm},
  fmTrUse in 'fmTrUse.pas' {TrUse},
  fmVisit in 'fmVisit.pas' {Visit},
  fmVisitReq in 'fmVisitReq.pas' {VisitReq},
  help in 'help.pas' {HtmlHelp},
  reDiskette in 'reDiskette.pas' {reSpecDiskette},
  rpRepBills in 'rpRepBills.pas' {RepBills},
  rpReportBills in 'rpReportBills.pas' {ReportBills},
  Splash in 'Splash.pas' {SplashForm},
  UFmShMsg in 'UFmShMsg.pas' {FmShowMessage},
  UnFillMenu in 'UnFillMenu.pas',
  UPDate in 'UPDate.pas',
  SCRLFORM in 'SCRLFORM.PAS' {scrollform},
  AmvSys_TLB in 'AmvSys_TLB.pas',
  InRadForms in '..\..\SharedUnits\InRadForms.pas' {InRadForm},
  fmSelCol4Print in '..\..\SharedUnits\fmSelCol4Print.pas' {SelCol4Print},
  fmSetting in '..\..\SharedUnits\fmSetting.pas' {Setting},
  CalculatorP in '..\..\SharedUnits\CalculatorP.pas' {CalculatorForm},
  Draw in '..\..\SharedUnits\Draw.pas' {FunctionF},
  SciCalc in '..\..\SharedUnits\SciCalc.pas' {SciCalcForm},
  fmGsnFrm in '..\..\SharedUnits\fmGsnFrm.pas' {GsnFrm},
  fmPassChanger in '..\..\SharedUnits\fmPassChanger.pas' {PassChanger},
  FormCommon in '..\..\SharedUnits\FormCommon.pas',
  fmPScrXP in '..\..\SharedUnits\fmPScrXP.pas' {XPPassWordDlg},
  fmPScr in '..\..\SharedUnits\fmPScr.pas' {PassWordDlg},
  fmPrintDialog in '..\..\SharedUnits\fmPrintDialog.pas' {PrintDialog},
  fmPrintSetting in '..\..\SharedUnits\fmPrintSetting.pas' {PrintSetting},
  BASEFRM in '..\..\SharedUnits\BASEFRM.pas' {BaseForm},
  fmMfrm in 'fmMfrm.pas' {MFrm},
  fmVerify in '..\..\SharedUnits\fmVerify.pas' {Verify},
  fmCatalog in '..\..\SharedUnits\fmCatalog.pas' {Catalog},
  fmNotes in '..\..\SharedUnits\fmNotes.pas' {Note},
  fmNEdit in '..\..\SharedUnits\fmNEdit.pas' {Nedit},
  RadDabDmdle in 'RadDabDmdle.pas' {RadDabData: TDataModule},
  DabDmdle in 'DabDmdle.pas' {DabData: TDataModule},
  fmRadMfrm in '..\..\SharedUnits\fmRadMfrm.pas',
  UCommon in '..\..\SharedUnits\UCommon.pas';

{$R *.TLB}

{$R *.RES}
begin
  AppplicationStart( '”Ì” „ Ã«„⁄ «„Ê«·');
end.
