unit fmReSpecAll;

interface

uses
  Windows, Messages, SysUtils, Classes, Graphics, Controls, Forms, Dialogs,
  ComCtrls, Grids, DBGrids,define,db, DBTables, DBCtrls, StdCtrls,
  ExtCtrls, Mask, Buttons, ADODB, ppCtrls, ppPrnabl, ppClass,
  ppModule, daDatMod, ppDB, ppDBPipe, ppBands, ppCache, ppComm, ppRelatv,
  ppProd, ppReport, ppViewr, ppVar, ppDBBDE, daDataVw, daQuery, daDBBDE,
  daQClass , DabDmdle, SmoothShow, RadForms, RSqllookup, RSQLComboBox,Variants,ppTypes;

type
  TreSpecAll = class(TRadForm)
    Panel1: TPanel;
    Panel2: TPanel;
    spbPreviewWhole: TSpeedButton;
    spbPreviewFirst: TSpeedButton;
    spbPreviewPrior: TSpeedButton;
    spbPreviewNext: TSpeedButton;
    spbPreviewLast: TSpeedButton;
    spbPreviewWidth: TSpeedButton;
    spbPreview100Percent: TSpeedButton;
    mskPreviewPage: TMaskEdit;
    mskPreviewPercentage: TMaskEdit;
    Panel4: TPanel;
    Label1: TLabel;
    ppviewer1: TppViewer;
    Label12: TLabel;
    Label11: TLabel;
    Label14: TLabel;
    Label2: TLabel;
    Label4: TLabel;
    dblUnit: TRSqlDbLookup;
    dblCostCenter: TRSqlDbLookup;
    dblLocCode: TRSqlDbLookup;
    dblEmp: TRSqlDbLookup;
    ppReport1: TppReport;
    ppTitleBand1: TppTitleBand;
    ppRepDate1: TppLabel;
    ppLabel8: TppLabel;
    ppLabel10: TppLabel;
    ppLabel15: TppLabel;
    ppLabel2: TppLabel;
    ppLabel11: TppLabel;
    ppUnit1: TppLabel;
    ppCostCenter1: TppLabel;
    ppLabel13: TppLabel;
    ppLocCode1: TppLabel;
    ppclass: TppLabel;
    ppEmp1: TppLabel;
    ppLabel25: TppLabel;
    ppLabel12: TppLabel;
    ppLabel14: TppLabel;
    ppSystemVariable1: TppSystemVariable;
    ppLabel21: TppLabel;
    ppSystemVariable2: TppSystemVariable;
    ppHeaderBand1: TppHeaderBand;
    ppShape1: TppShape;
    ppLabel3: TppLabel;
    ppLabel4: TppLabel;
    ppLabel6: TppLabel;
    ppLine2: TppLine;
    ppLine4: TppLine;
    ppLine6: TppLine;
    ppLine7: TppLine;
    ppLine10: TppLine;
    ppLine13: TppLine;
    ppLine15: TppLine;
    ppLine1: TppLine;
    ppLabel5: TppLabel;
    ppLine18: TppLine;
    ppLabel16: TppLabel;
    ppLabel17: TppLabel;
    ppLabel18: TppLabel;
    ppLabel19: TppLabel;
    ppLine22: TppLine;
    ppLine23: TppLine;
    ppLine24: TppLine;
    ppLine25: TppLine;
    ppLine26: TppLine;
    ppLine9: TppLine;
    ppLabel1: TppLabel;
    ppLabel20: TppLabel;
    ppLabel58: TppLabel;
    ppLabel22: TppLabel;
    ppLabel29: TppLabel;
    ppLabel30: TppLabel;
    ppLabel28: TppLabel;
    ppLine5: TppLine;
    ppLabel7: TppLabel;
    ppLabel9: TppLabel;
    ppDetailBand1: TppDetailBand;
    ppLine16: TppLine;
    ppLine17: TppLine;
    ppDBText1: TppDBText;
    ppRow1: TppDBText;
    ppDBText3: TppDBText;
    ppDBText5: TppDBText;
    ppLine20: TppLine;
    ppLine21: TppLine;
    ppLine3: TppLine;
    ppDBText4: TppDBText;
    ppLine27: TppLine;
    ppLine28: TppLine;
    ppLine29: TppLine;
    ppLine30: TppLine;
    ppLine31: TppLine;
    ppDBText6: TppDBText;
    ppDBText9: TppDBText;
    ppDBText10: TppDBText;
    ppDBText11: TppDBText;
    ppDBText12: TppDBText;
    ppLine8: TppLine;
    ppLine36: TppLine;
    ppLine42: TppLine;
    ppDBText7: TppDBText;
    ppDBText8: TppDBText;
    ppLine11: TppLine;
    ppDBText13: TppDBText;
    ppLine12: TppLine;
    ppFooterBand1: TppFooterBand;
    ppLabel45: TppLabel;
    ppLabel46: TppLabel;
    ppLabel47: TppLabel;
    ppLabel48: TppLabel;
    ppLabel49: TppLabel;
    ppLabel50: TppLabel;
    ppLabel51: TppLabel;
    ppLabel52: TppLabel;
    ppLabel53: TppLabel;
    ppLabel54: TppLabel;
    ppLabel55: TppLabel;
    ppLabel56: TppLabel;
    ppDBPipeline1: TppDBPipeline;
    dsSpecAntique: TDataSource;
    ppReport2: TppReport;
    ppTitleBand2: TppTitleBand;
    ppLabel23: TppLabel;
    ppLabel24: TppLabel;
    ppLabel26: TppLabel;
    ppLabel27: TppLabel;
    ppUnit2: TppLabel;
    ppRepDate2: TppLabel;
    ppLabel33: TppLabel;
    ppCostCenter2: TppLabel;
    ppLabel35: TppLabel;
    ppLabel36: TppLabel;
    ppLabel37: TppLabel;
    ppEmp2: TppLabel;
    ppLabel39: TppLabel;
    ppLabel40: TppLabel;
    ppSystemVariable3: TppSystemVariable;
    ppLabel41: TppLabel;
    ppSystemVariable4: TppSystemVariable;
    ppHeaderBand2: TppHeaderBand;
    ppShape2: TppShape;
    ppLabel42: TppLabel;
    ppLabel43: TppLabel;
    ppLabel44: TppLabel;
    ppLabel57: TppLabel;
    ppLine14: TppLine;
    ppLine19: TppLine;
    ppLine32: TppLine;
    ppLine33: TppLine;
    ppLine34: TppLine;
    ppLine35: TppLine;
    ppLine37: TppLine;
    ppLabel59: TppLabel;
    ppLabel60: TppLabel;
    ppLabel61: TppLabel;
    ppLine38: TppLine;
    ppLabel62: TppLabel;
    ppLine39: TppLine;
    ppLabel63: TppLabel;
    ppLabel64: TppLabel;
    ppLabel65: TppLabel;
    ppLabel66: TppLabel;
    ppLabel67: TppLabel;
    ppLabel68: TppLabel;
    ppLine40: TppLine;
    ppLine41: TppLine;
    ppLine43: TppLine;
    ppLine44: TppLine;
    ppLine45: TppLine;
    ppLine46: TppLine;
    ppLabel69: TppLabel;
    ppLabel70: TppLabel;
    ppLine47: TppLine;
    ppLine48: TppLine;
    ppLine49: TppLine;
    ppLabel71: TppLabel;
    ppDetailBand2: TppDetailBand;
    ppLine50: TppLine;
    ppLine51: TppLine;
    ppLine52: TppLine;
    ppLine53: TppLine;
    ppLine54: TppLine;
    ppLine55: TppLine;
    ppDBText14: TppDBText;
    ppRow2: TppDBText;
    ppDBText16: TppDBText;
    ppDBText17: TppDBText;
    ppDBText18: TppDBText;
    ppDBText19: TppDBText;
    ppLine56: TppLine;
    ppLine57: TppLine;
    ppLine58: TppLine;
    ppDBText20: TppDBText;
    ppLine59: TppLine;
    ppLine60: TppLine;
    ppLine61: TppLine;
    ppLine62: TppLine;
    ppLine63: TppLine;
    ppDBText21: TppDBText;
    ppDBText22: TppDBText;
    ppDBText23: TppDBText;
    ppDBText24: TppDBText;
    ppDBText25: TppDBText;
    ppDBText26: TppDBText;
    ppLine64: TppLine;
    ppDBText27: TppDBText;
    ppLine65: TppLine;
    ppFooterBand2: TppFooterBand;
    ppLabel72: TppLabel;
    ppLabel73: TppLabel;
    ppLabel74: TppLabel;
    ppLabel75: TppLabel;
    ppLabel76: TppLabel;
    ppLabel77: TppLabel;
    ppLabel78: TppLabel;
    ppLabel79: TppLabel;
    ppLabel80: TppLabel;
    ppLabel81: TppLabel;
    ppLabel82: TppLabel;
    ppLabel83: TppLabel;
    ppLabel84: TppLabel;
    ppLabel85: TppLabel;
    ppLabel86: TppLabel;
    ppLabel87: TppLabel;
    ppLabel88: TppLabel;
    ppLabel89: TppLabel;
    ppLabel90: TppLabel;
    ppLabel91: TppLabel;
    ppLabel92: TppLabel;
    ppLabel93: TppLabel;
    ppLabel94: TppLabel;
    ppLabel95: TppLabel;
    ppDBPipeline2: TppDBPipeline;
    ppField1: TppField;
    ppField2: TppField;
    ppField3: TppField;
    ppField4: TppField;
    ppField5: TppField;
    ppField6: TppField;
    ppField7: TppField;
    ppField8: TppField;
    ppField9: TppField;
    ppField10: TppField;
    ppField11: TppField;
    ppField12: TppField;
    ppField13: TppField;
    ppField14: TppField;
    ppField15: TppField;
    ppField16: TppField;
    ppField17: TppField;
    ppField18: TppField;
    ppField19: TppField;
    ppField20: TppField;
    ppDBPipeline1ppField21: TppField;
    ppDBPipeline1ppField22: TppField;
    ppDBPipeline1ppField23: TppField;
    ppDBPipeline1ppField24: TppField;
    ppDBPipeline1ppField25: TppField;
    ppDBPipeline1ppField26: TppField;
    ppDBPipeline1ppField27: TppField;
    ppDBPipeline1ppField28: TppField;
    ppDBPipeline1ppField29: TppField;
    ppDBPipeline1ppField30: TppField;
    dsSpecMuseum: TDataSource;
    ppReport3: TppReport;
    ppTitleBand3: TppTitleBand;
    ppLabel96: TppLabel;
    ppLabel97: TppLabel;
    ppLabel98: TppLabel;
    ppLabel99: TppLabel;
    ppUnit3: TppLabel;
    ppRepDate3: TppLabel;
    ppLabel102: TppLabel;
    ppCostCenter3: TppLabel;
    ppLabel104: TppLabel;
    ppLabel105: TppLabel;
    ppLabel106: TppLabel;
    ppEmp3: TppLabel;
    ppLabel108: TppLabel;
    ppLabel109: TppLabel;
    ppSystemVariable5: TppSystemVariable;
    ppLabel110: TppLabel;
    ppSystemVariable6: TppSystemVariable;
    ppHeaderBand3: TppHeaderBand;
    ppShape3: TppShape;
    ppLabel111: TppLabel;
    ppLabel112: TppLabel;
    ppLabel113: TppLabel;
    ppLabel114: TppLabel;
    ppLine66: TppLine;
    ppLine67: TppLine;
    ppLine68: TppLine;
    ppLine69: TppLine;
    ppLine70: TppLine;
    ppLine71: TppLine;
    ppLine72: TppLine;
    ppLabel115: TppLabel;
    ppLabel116: TppLabel;
    ppLabel117: TppLabel;
    ppLine73: TppLine;
    ppLabel118: TppLabel;
    ppLine74: TppLine;
    ppLabel119: TppLabel;
    ppLabel120: TppLabel;
    ppLabel121: TppLabel;
    ppLabel122: TppLabel;
    ppLabel123: TppLabel;
    ppLabel124: TppLabel;
    ppLine75: TppLine;
    ppLine76: TppLine;
    ppLine77: TppLine;
    ppLine78: TppLine;
    ppLine79: TppLine;
    ppLine80: TppLine;
    ppLabel125: TppLabel;
    ppLabel126: TppLabel;
    ppLine81: TppLine;
    ppLine82: TppLine;
    ppLine83: TppLine;
    ppLabel127: TppLabel;
    ppLabel128: TppLabel;
    ppDetailBand3: TppDetailBand;
    ppLine84: TppLine;
    ppLine85: TppLine;
    ppLine86: TppLine;
    ppLine87: TppLine;
    ppLine88: TppLine;
    ppLine89: TppLine;
    ppDBText28: TppDBText;
    ppRow3: TppDBText;
    ppDBText30: TppDBText;
    ppDBText31: TppDBText;
    ppDBText32: TppDBText;
    ppDBText33: TppDBText;
    ppLine90: TppLine;
    ppLine91: TppLine;
    ppLine92: TppLine;
    ppDBText34: TppDBText;
    ppLine93: TppLine;
    ppLine94: TppLine;
    ppLine95: TppLine;
    ppLine96: TppLine;
    ppLine97: TppLine;
    ppDBText35: TppDBText;
    ppDBText36: TppDBText;
    ppDBText37: TppDBText;
    ppDBText38: TppDBText;
    ppDBText39: TppDBText;
    ppDBText40: TppDBText;
    ppLine98: TppLine;
    ppDBText41: TppDBText;
    ppLine99: TppLine;
    ppFooterBand3: TppFooterBand;
    ppLabel129: TppLabel;
    ppLabel130: TppLabel;
    ppLabel131: TppLabel;
    ppLabel132: TppLabel;
    ppLabel133: TppLabel;
    ppLabel134: TppLabel;
    ppLabel135: TppLabel;
    ppLabel136: TppLabel;
    ppLabel137: TppLabel;
    ppLabel138: TppLabel;
    ppLabel139: TppLabel;
    ppLabel140: TppLabel;
    ppLabel141: TppLabel;
    ppLabel142: TppLabel;
    ppLabel143: TppLabel;
    ppLabel144: TppLabel;
    ppLabel145: TppLabel;
    ppLabel146: TppLabel;
    ppLabel147: TppLabel;
    ppLabel148: TppLabel;
    ppLabel149: TppLabel;
    ppLabel150: TppLabel;
    ppLabel151: TppLabel;
    ppLabel152: TppLabel;
    ppDBPipeline3: TppDBPipeline;
    ppField21: TppField;
    ppField22: TppField;
    ppField23: TppField;
    ppField24: TppField;
    ppField25: TppField;
    ppField26: TppField;
    ppField27: TppField;
    ppField28: TppField;
    ppField29: TppField;
    ppField30: TppField;
    ppField31: TppField;
    ppField32: TppField;
    ppField33: TppField;
    ppField34: TppField;
    ppField35: TppField;
    ppField36: TppField;
    ppField37: TppField;
    ppField38: TppField;
    ppField39: TppField;
    ppField40: TppField;
    ppField41: TppField;
    ppField42: TppField;
    ppField43: TppField;
    ppField44: TppField;
    ppField45: TppField;
    ppField46: TppField;
    dsSpecStamp: TDataSource;
    ppReport4: TppReport;
    ppTitleBand4: TppTitleBand;
    ppLabel153: TppLabel;
    ppLabel154: TppLabel;
    ppLabel155: TppLabel;
    ppLabel156: TppLabel;
    ppUnit4: TppLabel;
    ppRepDate4: TppLabel;
    ppLabel159: TppLabel;
    ppCostCenter4: TppLabel;
    ppLabel161: TppLabel;
    ppLabel162: TppLabel;
    ppLabel163: TppLabel;
    ppEmp4: TppLabel;
    ppLabel165: TppLabel;
    ppLabel166: TppLabel;
    ppSystemVariable7: TppSystemVariable;
    ppLabel167: TppLabel;
    ppSystemVariable8: TppSystemVariable;
    ppHeaderBand4: TppHeaderBand;
    ppShape4: TppShape;
    ppLabel168: TppLabel;
    ppLabel169: TppLabel;
    ppLabel170: TppLabel;
    ppLabel171: TppLabel;
    ppLine100: TppLine;
    ppLine101: TppLine;
    ppLine102: TppLine;
    ppLine103: TppLine;
    ppLine104: TppLine;
    ppLine105: TppLine;
    ppLine106: TppLine;
    ppLabel172: TppLabel;
    ppLabel173: TppLabel;
    ppLabel174: TppLabel;
    ppLine107: TppLine;
    ppLabel175: TppLabel;
    ppLine108: TppLine;
    ppLabel176: TppLabel;
    ppLabel177: TppLabel;
    ppLabel178: TppLabel;
    ppLabel179: TppLabel;
    ppLabel180: TppLabel;
    ppLabel181: TppLabel;
    ppLine109: TppLine;
    ppLine110: TppLine;
    ppLine111: TppLine;
    ppLine112: TppLine;
    ppLine113: TppLine;
    ppLine114: TppLine;
    ppLabel182: TppLabel;
    ppLabel183: TppLabel;
    ppLine115: TppLine;
    ppLine116: TppLine;
    ppLine117: TppLine;
    ppLabel184: TppLabel;
    ppLabel185: TppLabel;
    ppLabel186: TppLabel;
    ppLabel187: TppLabel;
    ppDetailBand4: TppDetailBand;
    ppLine118: TppLine;
    ppLine119: TppLine;
    ppLine120: TppLine;
    ppLine121: TppLine;
    ppLine122: TppLine;
    ppLine123: TppLine;
    ppDBText42: TppDBText;
    ppRow4: TppDBText;
    ppDBText44: TppDBText;
    ppDBText45: TppDBText;
    ppDBText46: TppDBText;
    ppDBText47: TppDBText;
    ppLine124: TppLine;
    ppLine125: TppLine;
    ppLine126: TppLine;
    ppDBText48: TppDBText;
    ppLine127: TppLine;
    ppLine128: TppLine;
    ppLine129: TppLine;
    ppLine130: TppLine;
    ppLine131: TppLine;
    ppDBText49: TppDBText;
    ppDBText50: TppDBText;
    ppDBText51: TppDBText;
    ppDBText52: TppDBText;
    ppDBText53: TppDBText;
    ppDBText54: TppDBText;
    ppLine132: TppLine;
    ppDBText55: TppDBText;
    ppLine133: TppLine;
    ppFooterBand4: TppFooterBand;
    ppLabel188: TppLabel;
    ppLabel189: TppLabel;
    ppLabel190: TppLabel;
    ppLabel191: TppLabel;
    ppLabel192: TppLabel;
    ppLabel193: TppLabel;
    ppLabel194: TppLabel;
    ppLabel195: TppLabel;
    ppLabel196: TppLabel;
    ppLabel197: TppLabel;
    ppLabel198: TppLabel;
    ppLabel199: TppLabel;
    ppLabel200: TppLabel;
    ppLabel201: TppLabel;
    ppLabel202: TppLabel;
    ppLabel203: TppLabel;
    ppLabel204: TppLabel;
    ppLabel205: TppLabel;
    ppLabel206: TppLabel;
    ppLabel207: TppLabel;
    ppLabel208: TppLabel;
    ppLabel209: TppLabel;
    ppLabel210: TppLabel;
    ppLabel211: TppLabel;
    ppDBPipeline4: TppDBPipeline;
    ppField47: TppField;
    ppField48: TppField;
    ppField49: TppField;
    ppField50: TppField;
    ppField51: TppField;
    ppField52: TppField;
    ppField53: TppField;
    ppField54: TppField;
    ppField55: TppField;
    ppField56: TppField;
    ppField57: TppField;
    ppField58: TppField;
    ppField59: TppField;
    ppField60: TppField;
    ppField61: TppField;
    ppField62: TppField;
    ppField63: TppField;
    ppField64: TppField;
    ppField65: TppField;
    ppField66: TppField;
    ppField67: TppField;
    ppField68: TppField;
    ppField69: TppField;
    dsSpecRide: TDataSource;
    dsSpecLab: TDataSource;
    ppDBPipeline5: TppDBPipeline;
    ppField70: TppField;
    ppField71: TppField;
    ppField72: TppField;
    ppField73: TppField;
    ppField74: TppField;
    ppField75: TppField;
    ppField76: TppField;
    ppField77: TppField;
    ppField78: TppField;
    ppField79: TppField;
    ppField80: TppField;
    ppField81: TppField;
    ppField82: TppField;
    ppField83: TppField;
    ppField84: TppField;
    ppField85: TppField;
    ppField86: TppField;
    ppReport5: TppReport;
    ppTitleBand5: TppTitleBand;
    ppLabel212: TppLabel;
    ppLabel213: TppLabel;
    ppLabel214: TppLabel;
    ppLabel215: TppLabel;
    ppUnit5: TppLabel;
    ppRepDate5: TppLabel;
    ppLabel218: TppLabel;
    ppCostCenter5: TppLabel;
    ppLabel220: TppLabel;
    ppLabel221: TppLabel;
    ppLabel222: TppLabel;
    ppEmp5: TppLabel;
    ppLabel224: TppLabel;
    ppLabel225: TppLabel;
    ppSystemVariable9: TppSystemVariable;
    ppLabel226: TppLabel;
    ppSystemVariable10: TppSystemVariable;
    ppHeaderBand5: TppHeaderBand;
    ppShape5: TppShape;
    ppLabel227: TppLabel;
    ppLabel228: TppLabel;
    ppLabel229: TppLabel;
    ppLabel230: TppLabel;
    ppLine134: TppLine;
    ppLine135: TppLine;
    ppLine136: TppLine;
    ppLine137: TppLine;
    ppLine138: TppLine;
    ppLine139: TppLine;
    ppLine140: TppLine;
    ppLabel231: TppLabel;
    ppLabel232: TppLabel;
    ppLabel233: TppLabel;
    ppLine141: TppLine;
    ppLabel234: TppLabel;
    ppLine142: TppLine;
    ppLabel235: TppLabel;
    ppLabel236: TppLabel;
    ppLabel237: TppLabel;
    ppLabel238: TppLabel;
    ppLabel239: TppLabel;
    ppLabel240: TppLabel;
    ppLine143: TppLine;
    ppLine144: TppLine;
    ppLine145: TppLine;
    ppLine146: TppLine;
    ppLine147: TppLine;
    ppLine148: TppLine;
    ppLabel241: TppLabel;
    ppLabel242: TppLabel;
    ppLine149: TppLine;
    ppLine150: TppLine;
    ppLabel243: TppLabel;
    ppDetailBand5: TppDetailBand;
    ppLine151: TppLine;
    ppLine152: TppLine;
    ppLine153: TppLine;
    ppLine154: TppLine;
    ppLine155: TppLine;
    ppDBText56: TppDBText;
    ppRow5: TppDBText;
    ppDBText58: TppDBText;
    ppDBText59: TppDBText;
    ppDBText60: TppDBText;
    ppLine156: TppLine;
    ppLine157: TppLine;
    ppLine158: TppLine;
    ppDBText61: TppDBText;
    ppLine159: TppLine;
    ppLine160: TppLine;
    ppLine161: TppLine;
    ppLine162: TppLine;
    ppLine163: TppLine;
    ppDBText62: TppDBText;
    ppDBText63: TppDBText;
    ppDBText64: TppDBText;
    ppDBText65: TppDBText;
    ppDBText66: TppDBText;
    ppDBText67: TppDBText;
    ppLine164: TppLine;
    ppDBText68: TppDBText;
    ppLine165: TppLine;
    ppFooterBand5: TppFooterBand;
    ppLabel244: TppLabel;
    ppLabel245: TppLabel;
    ppLabel246: TppLabel;
    ppLabel247: TppLabel;
    ppLabel248: TppLabel;
    ppLabel249: TppLabel;
    ppLabel250: TppLabel;
    ppLabel251: TppLabel;
    ppLabel252: TppLabel;
    ppLabel253: TppLabel;
    ppLabel254: TppLabel;
    ppLabel255: TppLabel;
    ppLabel256: TppLabel;
    ppLabel257: TppLabel;
    ppLabel258: TppLabel;
    ppLabel259: TppLabel;
    ppLabel260: TppLabel;
    ppLabel261: TppLabel;
    ppLabel262: TppLabel;
    ppLabel263: TppLabel;
    ppLabel264: TppLabel;
    ppLabel265: TppLabel;
    ppLabel266: TppLabel;
    ppLabel267: TppLabel;
    ppReport6: TppReport;
    ppTitleBand6: TppTitleBand;
    ppLabel268: TppLabel;
    ppLabel269: TppLabel;
    ppLabel270: TppLabel;
    ppLabel271: TppLabel;
    ppUnit6: TppLabel;
    ppRepDate6: TppLabel;
    ppLabel274: TppLabel;
    ppCostCenter6: TppLabel;
    ppLabel276: TppLabel;
    ppLabel277: TppLabel;
    ppLabel278: TppLabel;
    ppEmp6: TppLabel;
    ppLabel280: TppLabel;
    ppLabel281: TppLabel;
    ppSystemVariable11: TppSystemVariable;
    ppLabel282: TppLabel;
    ppSystemVariable12: TppSystemVariable;
    ppHeaderBand6: TppHeaderBand;
    ppShape6: TppShape;
    ppLabel283: TppLabel;
    ppLabel284: TppLabel;
    ppLabel285: TppLabel;
    ppLabel286: TppLabel;
    ppLine166: TppLine;
    ppLine167: TppLine;
    ppLine168: TppLine;
    ppLine169: TppLine;
    ppLine170: TppLine;
    ppLine171: TppLine;
    ppLine172: TppLine;
    ppLine173: TppLine;
    ppLabel287: TppLabel;
    ppLabel288: TppLabel;
    ppLabel289: TppLabel;
    ppLine174: TppLine;
    ppLabel290: TppLabel;
    ppLine175: TppLine;
    ppLabel291: TppLabel;
    ppLabel292: TppLabel;
    ppLabel293: TppLabel;
    ppLabel294: TppLabel;
    ppLabel295: TppLabel;
    ppLabel296: TppLabel;
    ppLabel297: TppLabel;
    ppLabel298: TppLabel;
    ppLine176: TppLine;
    ppLine177: TppLine;
    ppLine178: TppLine;
    ppLine179: TppLine;
    ppLine180: TppLine;
    ppDetailBand6: TppDetailBand;
    ppLine181: TppLine;
    ppLine182: TppLine;
    ppLine183: TppLine;
    ppLine184: TppLine;
    ppLine185: TppLine;
    ppLine186: TppLine;
    ppDBText69: TppDBText;
    ppRow6: TppDBText;
    ppDBText71: TppDBText;
    ppDBText72: TppDBText;
    ppDBText73: TppDBText;
    ppDBText74: TppDBText;
    ppLine187: TppLine;
    ppLine188: TppLine;
    ppLine189: TppLine;
    ppDBText75: TppDBText;
    ppLine190: TppLine;
    ppLine191: TppLine;
    ppLine192: TppLine;
    ppLine193: TppLine;
    ppLine194: TppLine;
    ppDBText76: TppDBText;
    ppDBText77: TppDBText;
    ppDBText78: TppDBText;
    ppDBText79: TppDBText;
    ppDBText80: TppDBText;
    ppFooterBand6: TppFooterBand;
    ppLabel299: TppLabel;
    ppLabel300: TppLabel;
    ppLabel301: TppLabel;
    ppLabel302: TppLabel;
    ppLabel303: TppLabel;
    ppLabel304: TppLabel;
    ppLabel305: TppLabel;
    ppLabel306: TppLabel;
    ppLabel307: TppLabel;
    ppLabel308: TppLabel;
    ppLabel309: TppLabel;
    ppLabel310: TppLabel;
    ppLabel311: TppLabel;
    ppLabel312: TppLabel;
    ppLabel313: TppLabel;
    ppLabel314: TppLabel;
    ppLabel315: TppLabel;
    ppLabel316: TppLabel;
    ppLabel317: TppLabel;
    ppLabel318: TppLabel;
    ppLabel319: TppLabel;
    ppLabel320: TppLabel;
    ppLabel321: TppLabel;
    ppLabel322: TppLabel;
    ppDBPipeline6: TppDBPipeline;
    ppField87: TppField;
    ppField88: TppField;
    ppField89: TppField;
    ppField90: TppField;
    ppField91: TppField;
    ppField92: TppField;
    ppField93: TppField;
    ppField94: TppField;
    ppField95: TppField;
    ppField96: TppField;
    ppField97: TppField;
    ppField98: TppField;
    ppField99: TppField;
    ppField100: TppField;
    ppField101: TppField;
    ppField102: TppField;
    ppField103: TppField;
    dsSpecMachine: TDataSource;
    ppReport7: TppReport;
    ppTitleBand7: TppTitleBand;
    ppLabel323: TppLabel;
    ppLabel324: TppLabel;
    ppLabel325: TppLabel;
    ppLabel326: TppLabel;
    ppUnit7: TppLabel;
    ppRepDate7: TppLabel;
    ppLabel329: TppLabel;
    ppCostCenter7: TppLabel;
    ppLabel331: TppLabel;
    ppLabel332: TppLabel;
    ppLabel333: TppLabel;
    ppEmp7: TppLabel;
    ppLabel335: TppLabel;
    ppLabel336: TppLabel;
    ppSystemVariable13: TppSystemVariable;
    ppLabel337: TppLabel;
    ppSystemVariable14: TppSystemVariable;
    ppHeaderBand7: TppHeaderBand;
    ppShape7: TppShape;
    ppLabel338: TppLabel;
    ppLabel339: TppLabel;
    ppLabel340: TppLabel;
    ppLabel341: TppLabel;
    ppLine195: TppLine;
    ppLine196: TppLine;
    ppLine197: TppLine;
    ppLine198: TppLine;
    ppLine199: TppLine;
    ppLine200: TppLine;
    ppLine201: TppLine;
    ppLabel342: TppLabel;
    ppLabel343: TppLabel;
    ppLabel344: TppLabel;
    ppLine202: TppLine;
    ppLabel345: TppLabel;
    ppLine203: TppLine;
    ppLabel346: TppLabel;
    ppLabel347: TppLabel;
    ppLabel348: TppLabel;
    ppLabel349: TppLabel;
    ppLabel350: TppLabel;
    ppLabel351: TppLabel;
    ppLine204: TppLine;
    ppLine205: TppLine;
    ppLine206: TppLine;
    ppLine207: TppLine;
    ppLine208: TppLine;
    ppLine209: TppLine;
    ppLabel352: TppLabel;
    ppLabel353: TppLabel;
    ppLine210: TppLine;
    ppLine211: TppLine;
    ppLine212: TppLine;
    ppLabel354: TppLabel;
    ppDetailBand7: TppDetailBand;
    ppLine213: TppLine;
    ppLine214: TppLine;
    ppLine215: TppLine;
    ppLine216: TppLine;
    ppLine217: TppLine;
    ppLine218: TppLine;
    ppDBText81: TppDBText;
    ppRow7: TppDBText;
    ppDBText83: TppDBText;
    ppDBText84: TppDBText;
    ppDBText85: TppDBText;
    ppDBText86: TppDBText;
    ppLine219: TppLine;
    ppLine220: TppLine;
    ppLine221: TppLine;
    ppDBText87: TppDBText;
    ppLine222: TppLine;
    ppLine223: TppLine;
    ppLine224: TppLine;
    ppLine225: TppLine;
    ppLine226: TppLine;
    ppDBText88: TppDBText;
    ppDBText89: TppDBText;
    ppDBText90: TppDBText;
    ppDBText91: TppDBText;
    ppDBText92: TppDBText;
    ppDBText93: TppDBText;
    ppLine227: TppLine;
    ppDBText94: TppDBText;
    ppLine228: TppLine;
    ppFooterBand7: TppFooterBand;
    ppLabel355: TppLabel;
    ppLabel356: TppLabel;
    ppLabel357: TppLabel;
    ppLabel358: TppLabel;
    ppLabel359: TppLabel;
    ppLabel360: TppLabel;
    ppLabel361: TppLabel;
    ppLabel362: TppLabel;
    ppLabel363: TppLabel;
    ppLabel364: TppLabel;
    ppLabel365: TppLabel;
    ppLabel366: TppLabel;
    ppLabel367: TppLabel;
    ppLabel368: TppLabel;
    ppLabel369: TppLabel;
    ppLabel370: TppLabel;
    ppLabel371: TppLabel;
    ppLabel372: TppLabel;
    ppLabel373: TppLabel;
    ppLabel374: TppLabel;
    ppLabel375: TppLabel;
    ppLabel376: TppLabel;
    ppLabel377: TppLabel;
    ppLabel378: TppLabel;
    ppDBPipeline7: TppDBPipeline;
    ppField104: TppField;
    ppField105: TppField;
    ppField106: TppField;
    ppField107: TppField;
    ppField108: TppField;
    ppField109: TppField;
    ppField110: TppField;
    ppField111: TppField;
    ppField112: TppField;
    ppField113: TppField;
    ppField114: TppField;
    ppField115: TppField;
    ppField116: TppField;
    ppField117: TppField;
    ppField118: TppField;
    ppField119: TppField;
    ppField120: TppField;
    ppField121: TppField;
    ppField122: TppField;
    ppField123: TppField;
    ppField124: TppField;
    ppField125: TppField;
    ppField126: TppField;
    ppField127: TppField;
    ppField128: TppField;
    dsSpecBooks: TDataSource;
    ppReport8: TppReport;
    ppTitleBand8: TppTitleBand;
    ppLabel379: TppLabel;
    ppLabel380: TppLabel;
    ppLabel381: TppLabel;
    ppLabel382: TppLabel;
    ppUnit8: TppLabel;
    ppRepDate8: TppLabel;
    ppLabel385: TppLabel;
    ppCostCenter8: TppLabel;
    ppLabel387: TppLabel;
    ppLabel388: TppLabel;
    ppLabel389: TppLabel;
    ppEmp8: TppLabel;
    ppLabel391: TppLabel;
    ppLabel392: TppLabel;
    ppSystemVariable15: TppSystemVariable;
    ppLabel393: TppLabel;
    ppSystemVariable16: TppSystemVariable;
    ppHeaderBand8: TppHeaderBand;
    ppShape8: TppShape;
    ppLabel394: TppLabel;
    ppLabel395: TppLabel;
    ppLabel396: TppLabel;
    ppLabel397: TppLabel;
    ppLine229: TppLine;
    ppLine230: TppLine;
    ppLine231: TppLine;
    ppLine232: TppLine;
    ppLine233: TppLine;
    ppLine234: TppLine;
    ppLine235: TppLine;
    ppLabel398: TppLabel;
    ppLabel399: TppLabel;
    ppLabel400: TppLabel;
    ppLine236: TppLine;
    ppLabel401: TppLabel;
    ppLine237: TppLine;
    ppLabel402: TppLabel;
    ppLabel403: TppLabel;
    ppLabel404: TppLabel;
    ppLabel405: TppLabel;
    ppLabel406: TppLabel;
    ppLine238: TppLine;
    ppLine239: TppLine;
    ppLine240: TppLine;
    ppLine241: TppLine;
    ppLine242: TppLine;
    ppLine243: TppLine;
    ppLabel407: TppLabel;
    ppLabel408: TppLabel;
    ppLine244: TppLine;
    ppLine245: TppLine;
    ppLine246: TppLine;
    ppLabel409: TppLabel;
    ppLabel410: TppLabel;
    ppDetailBand8: TppDetailBand;
    ppLine247: TppLine;
    ppLine248: TppLine;
    ppLine249: TppLine;
    ppLine250: TppLine;
    ppLine251: TppLine;
    ppLine252: TppLine;
    ppDBText95: TppDBText;
    ppRow8: TppDBText;
    ppDBText97: TppDBText;
    ppDBText98: TppDBText;
    ppDBText99: TppDBText;
    ppDBText100: TppDBText;
    ppLine253: TppLine;
    ppLine254: TppLine;
    ppLine255: TppLine;
    ppDBText101: TppDBText;
    ppLine256: TppLine;
    ppLine257: TppLine;
    ppLine258: TppLine;
    ppLine259: TppLine;
    ppLine260: TppLine;
    ppDBText102: TppDBText;
    ppDBText103: TppDBText;
    ppDBText104: TppDBText;
    ppDBText105: TppDBText;
    ppDBText106: TppDBText;
    ppDBText107: TppDBText;
    ppLine261: TppLine;
    ppDBText108: TppDBText;
    ppLine262: TppLine;
    ppFooterBand8: TppFooterBand;
    ppLabel411: TppLabel;
    ppLabel412: TppLabel;
    ppLabel413: TppLabel;
    ppLabel414: TppLabel;
    ppLabel415: TppLabel;
    ppLabel416: TppLabel;
    ppLabel417: TppLabel;
    ppLabel418: TppLabel;
    ppLabel419: TppLabel;
    ppLabel420: TppLabel;
    ppLabel421: TppLabel;
    ppLabel422: TppLabel;
    ppLabel423: TppLabel;
    ppLabel424: TppLabel;
    ppLabel425: TppLabel;
    ppLabel426: TppLabel;
    ppLabel427: TppLabel;
    ppLabel428: TppLabel;
    ppLabel429: TppLabel;
    ppLabel430: TppLabel;
    ppLabel431: TppLabel;
    ppLabel432: TppLabel;
    ppLabel433: TppLabel;
    ppLabel434: TppLabel;
    ppDBPipeline8: TppDBPipeline;
    ppField129: TppField;
    ppField130: TppField;
    ppField131: TppField;
    ppField132: TppField;
    ppField133: TppField;
    ppField134: TppField;
    ppField135: TppField;
    ppField136: TppField;
    ppField137: TppField;
    ppField138: TppField;
    ppField139: TppField;
    ppField140: TppField;
    ppField141: TppField;
    ppField142: TppField;
    ppField143: TppField;
    ppField144: TppField;
    ppField145: TppField;
    ppField146: TppField;
    dsSpecLens: TDataSource;
    ppReport9: TppReport;
    ppTitleBand9: TppTitleBand;
    ppLabel435: TppLabel;
    ppLabel436: TppLabel;
    ppLabel437: TppLabel;
    ppLabel438: TppLabel;
    ppUnit9: TppLabel;
    ppRepDate9: TppLabel;
    ppLabel441: TppLabel;
    ppCostCenter9: TppLabel;
    ppLabel443: TppLabel;
    ppLabel444: TppLabel;
    ppLabel445: TppLabel;
    ppLabel446: TppLabel;
    ppEmp9: TppLabel;
    ppLabel448: TppLabel;
    ppSystemVariable17: TppSystemVariable;
    ppLabel449: TppLabel;
    ppSystemVariable18: TppSystemVariable;
    ppHeaderBand9: TppHeaderBand;
    ppShape9: TppShape;
    ppLabel450: TppLabel;
    ppLabel451: TppLabel;
    ppLabel452: TppLabel;
    ppLabel453: TppLabel;
    ppLine263: TppLine;
    ppLine264: TppLine;
    ppLine265: TppLine;
    ppLine266: TppLine;
    ppLine267: TppLine;
    ppLine268: TppLine;
    ppLine269: TppLine;
    ppLabel454: TppLabel;
    ppLabel455: TppLabel;
    ppLabel456: TppLabel;
    ppLine270: TppLine;
    ppLabel457: TppLabel;
    ppLine271: TppLine;
    ppLabel458: TppLabel;
    ppLabel459: TppLabel;
    ppLabel460: TppLabel;
    ppLabel461: TppLabel;
    ppLabel462: TppLabel;
    ppLine272: TppLine;
    ppLine273: TppLine;
    ppLine274: TppLine;
    ppLine275: TppLine;
    ppLine276: TppLine;
    ppLine277: TppLine;
    ppLabel463: TppLabel;
    ppLabel464: TppLabel;
    ppLine278: TppLine;
    ppLine279: TppLine;
    ppLine280: TppLine;
    ppLabel465: TppLabel;
    ppLabel466: TppLabel;
    ppDetailBand9: TppDetailBand;
    ppLine281: TppLine;
    ppLine282: TppLine;
    ppLine283: TppLine;
    ppLine284: TppLine;
    ppLine285: TppLine;
    ppLine286: TppLine;
    ppDBText109: TppDBText;
    ppRow9: TppDBText;
    ppDBText111: TppDBText;
    ppDBText112: TppDBText;
    ppDBText113: TppDBText;
    ppDBText114: TppDBText;
    ppLine287: TppLine;
    ppLine288: TppLine;
    ppLine289: TppLine;
    ppDBText115: TppDBText;
    ppLine290: TppLine;
    ppLine291: TppLine;
    ppLine292: TppLine;
    ppLine293: TppLine;
    ppLine294: TppLine;
    ppDBText116: TppDBText;
    ppDBText117: TppDBText;
    ppDBText118: TppDBText;
    ppDBText119: TppDBText;
    ppDBText120: TppDBText;
    ppDBText121: TppDBText;
    ppLine295: TppLine;
    ppDBText122: TppDBText;
    ppLine296: TppLine;
    ppFooterBand9: TppFooterBand;
    ppLabel467: TppLabel;
    ppLabel468: TppLabel;
    ppLabel469: TppLabel;
    ppLabel470: TppLabel;
    ppLabel471: TppLabel;
    ppLabel472: TppLabel;
    ppLabel473: TppLabel;
    ppLabel474: TppLabel;
    ppLabel475: TppLabel;
    ppLabel476: TppLabel;
    ppLabel477: TppLabel;
    ppLabel478: TppLabel;
    ppLabel479: TppLabel;
    ppLabel480: TppLabel;
    ppLabel481: TppLabel;
    ppLabel482: TppLabel;
    ppLabel483: TppLabel;
    ppLabel484: TppLabel;
    ppLabel485: TppLabel;
    ppLabel486: TppLabel;
    ppLabel487: TppLabel;
    ppLabel488: TppLabel;
    ppLabel489: TppLabel;
    ppLabel490: TppLabel;
    ppDBPipeline9: TppDBPipeline;
    ppDBPipeline9ppField1: TppField;
    ppDBPipeline9ppField2: TppField;
    ppDBPipeline9ppField3: TppField;
    ppDBPipeline9ppField4: TppField;
    ppDBPipeline9ppField5: TppField;
    ppDBPipeline9ppField6: TppField;
    ppDBPipeline9ppField7: TppField;
    ppDBPipeline9ppField8: TppField;
    ppDBPipeline9ppField9: TppField;
    ppDBPipeline9ppField10: TppField;
    ppDBPipeline9ppField11: TppField;
    ppDBPipeline9ppField12: TppField;
    ppDBPipeline9ppField13: TppField;
    ppDBPipeline9ppField14: TppField;
    ppDBPipeline9ppField15: TppField;
    ppDBPipeline9ppField16: TppField;
    ppDBPipeline9ppField17: TppField;
    ppDBPipeline9ppField18: TppField;
    ppDBPipeline9ppField19: TppField;
    ppDBPipeline9ppField20: TppField;
    ppDBPipeline9ppField21: TppField;
    ppDBPipeline9ppField22: TppField;
    dsSpecTextile: TDataSource;
    dsSpecDiskette: TDataSource;
    ppDBPipeline10: TppDBPipeline;
    ppField147: TppField;
    ppField148: TppField;
    ppField149: TppField;
    ppField150: TppField;
    ppField151: TppField;
    ppField152: TppField;
    ppField153: TppField;
    ppField154: TppField;
    ppField155: TppField;
    ppField156: TppField;
    ppField157: TppField;
    ppField158: TppField;
    ppField159: TppField;
    ppField160: TppField;
    ppField161: TppField;
    ppField162: TppField;
    ppField163: TppField;
    ppField164: TppField;
    ppField165: TppField;
    ppField166: TppField;
    ppReport10: TppReport;
    ppTitleBand10: TppTitleBand;
    ppLabel491: TppLabel;
    ppLabel492: TppLabel;
    ppLabel493: TppLabel;
    ppLabel494: TppLabel;
    ppUnit10: TppLabel;
    ppRepDate10: TppLabel;
    ppLabel497: TppLabel;
    ppCostCenter10: TppLabel;
    ppLabel499: TppLabel;
    ppLabel500: TppLabel;
    ppLabel501: TppLabel;
    ppEmp10: TppLabel;
    ppLabel503: TppLabel;
    ppLabel504: TppLabel;
    ppSystemVariable19: TppSystemVariable;
    ppLabel505: TppLabel;
    ppSystemVariable20: TppSystemVariable;
    ppHeaderBand10: TppHeaderBand;
    ppShape10: TppShape;
    ppLabel506: TppLabel;
    ppLabel507: TppLabel;
    ppLabel508: TppLabel;
    ppLabel509: TppLabel;
    ppLine297: TppLine;
    ppLine298: TppLine;
    ppLine299: TppLine;
    ppLine300: TppLine;
    ppLine301: TppLine;
    ppLine302: TppLine;
    ppLine303: TppLine;
    ppLabel510: TppLabel;
    ppLabel511: TppLabel;
    ppLine304: TppLine;
    ppLabel512: TppLabel;
    ppLine305: TppLine;
    ppLabel513: TppLabel;
    ppLabel514: TppLabel;
    ppLabel515: TppLabel;
    ppLabel516: TppLabel;
    ppLabel517: TppLabel;
    ppLine306: TppLine;
    ppLine307: TppLine;
    ppLine308: TppLine;
    ppLine309: TppLine;
    ppLine310: TppLine;
    ppLine311: TppLine;
    ppLabel518: TppLabel;
    ppLabel519: TppLabel;
    ppLine312: TppLine;
    ppLine313: TppLine;
    ppLabel520: TppLabel;
    ppLabel521: TppLabel;
    ppDetailBand10: TppDetailBand;
    ppLine314: TppLine;
    ppLine315: TppLine;
    ppLine316: TppLine;
    ppLine317: TppLine;
    ppLine318: TppLine;
    ppLine319: TppLine;
    ppDBText123: TppDBText;
    ppRow10: TppDBText;
    ppDBText125: TppDBText;
    ppDBText126: TppDBText;
    ppDBText127: TppDBText;
    ppLine320: TppLine;
    ppLine321: TppLine;
    ppLine322: TppLine;
    ppDBText128: TppDBText;
    ppLine323: TppLine;
    ppLine324: TppLine;
    ppLine325: TppLine;
    ppLine326: TppLine;
    ppLine327: TppLine;
    ppDBText129: TppDBText;
    ppDBText130: TppDBText;
    ppDBText131: TppDBText;
    ppDBText132: TppDBText;
    ppDBText133: TppDBText;
    ppDBText134: TppDBText;
    ppDBText135: TppDBText;
    ppLine328: TppLine;
    ppFooterBand10: TppFooterBand;
    ppLabel522: TppLabel;
    ppLabel523: TppLabel;
    ppLabel524: TppLabel;
    ppLabel525: TppLabel;
    ppLabel526: TppLabel;
    ppLabel527: TppLabel;
    ppLabel528: TppLabel;
    ppLabel529: TppLabel;
    ppLabel530: TppLabel;
    ppLabel531: TppLabel;
    ppLabel532: TppLabel;
    ppLabel533: TppLabel;
    ppLabel534: TppLabel;
    ppLabel535: TppLabel;
    ppLabel536: TppLabel;
    ppLabel537: TppLabel;
    ppLabel538: TppLabel;
    ppLabel539: TppLabel;
    ppLabel540: TppLabel;
    ppLabel541: TppLabel;
    ppLabel542: TppLabel;
    ppLabel543: TppLabel;
    ppLabel544: TppLabel;
    ppLabel545: TppLabel;
    dsSpecTaxidermy: TDataSource;
    ppDBPipeline11: TppDBPipeline;
    ppField167: TppField;
    ppField168: TppField;
    ppField169: TppField;
    ppField170: TppField;
    ppField171: TppField;
    ppField172: TppField;
    ppField173: TppField;
    ppField174: TppField;
    ppField175: TppField;
    ppField176: TppField;
    ppField177: TppField;
    ppField178: TppField;
    ppField179: TppField;
    ppField180: TppField;
    ppField181: TppField;
    ppField182: TppField;
    ppField183: TppField;
    ppReport11: TppReport;
    ppTitleBand11: TppTitleBand;
    ppLabel546: TppLabel;
    ppLabel547: TppLabel;
    ppLabel548: TppLabel;
    ppLabel549: TppLabel;
    ppUnit11: TppLabel;
    ppRepDate11: TppLabel;
    ppLabel552: TppLabel;
    ppCostCenter11: TppLabel;
    ppLabel554: TppLabel;
    ppLabel555: TppLabel;
    ppLabel556: TppLabel;
    ppEmp11: TppLabel;
    ppLabel558: TppLabel;
    ppLabel559: TppLabel;
    ppSystemVariable21: TppSystemVariable;
    ppLabel560: TppLabel;
    ppSystemVariable22: TppSystemVariable;
    ppHeaderBand11: TppHeaderBand;
    ppShape11: TppShape;
    ppLabel561: TppLabel;
    ppLabel562: TppLabel;
    ppLabel563: TppLabel;
    ppLabel564: TppLabel;
    ppLine329: TppLine;
    ppLine330: TppLine;
    ppLine331: TppLine;
    ppLine332: TppLine;
    ppLine333: TppLine;
    ppLine334: TppLine;
    ppLine335: TppLine;
    ppLabel565: TppLabel;
    ppLabel566: TppLabel;
    ppLine336: TppLine;
    ppLabel567: TppLabel;
    ppLine337: TppLine;
    ppLabel568: TppLabel;
    ppLabel569: TppLabel;
    ppLabel570: TppLabel;
    ppLabel571: TppLabel;
    ppLabel572: TppLabel;
    ppLine338: TppLine;
    ppLine339: TppLine;
    ppLine340: TppLine;
    ppLine341: TppLine;
    ppLine342: TppLine;
    ppLine343: TppLine;
    ppLabel573: TppLabel;
    ppLabel574: TppLabel;
    ppLine344: TppLine;
    ppLine345: TppLine;
    ppLabel575: TppLabel;
    ppLabel576: TppLabel;
    ppDetailBand11: TppDetailBand;
    ppLine346: TppLine;
    ppLine347: TppLine;
    ppLine348: TppLine;
    ppLine349: TppLine;
    ppLine350: TppLine;
    ppLine351: TppLine;
    ppDBText136: TppDBText;
    ppRow11: TppDBText;
    ppDBText138: TppDBText;
    ppDBText139: TppDBText;
    ppDBText140: TppDBText;
    ppLine352: TppLine;
    ppLine353: TppLine;
    ppLine354: TppLine;
    ppDBText141: TppDBText;
    ppLine355: TppLine;
    ppLine356: TppLine;
    ppLine357: TppLine;
    ppLine358: TppLine;
    ppLine359: TppLine;
    ppDBText142: TppDBText;
    ppDBText143: TppDBText;
    ppDBText144: TppDBText;
    ppDBText145: TppDBText;
    ppDBText146: TppDBText;
    ppDBText147: TppDBText;
    ppDBText148: TppDBText;
    ppLine360: TppLine;
    ppFooterBand11: TppFooterBand;
    ppLabel577: TppLabel;
    ppLabel578: TppLabel;
    ppLabel579: TppLabel;
    ppLabel580: TppLabel;
    ppLabel581: TppLabel;
    ppLabel582: TppLabel;
    ppLabel583: TppLabel;
    ppLabel584: TppLabel;
    ppLabel585: TppLabel;
    ppLabel586: TppLabel;
    ppLabel587: TppLabel;
    ppLabel588: TppLabel;
    ppLabel589: TppLabel;
    ppLabel590: TppLabel;
    ppLabel591: TppLabel;
    ppLabel592: TppLabel;
    ppLabel593: TppLabel;
    ppLabel594: TppLabel;
    ppLabel595: TppLabel;
    ppLabel596: TppLabel;
    ppLabel597: TppLabel;
    ppLabel598: TppLabel;
    ppLabel599: TppLabel;
    ppLabel600: TppLabel;
    ppReport12: TppReport;
    ppTitleBand12: TppTitleBand;
    ppLabel601: TppLabel;
    ppLabel602: TppLabel;
    ppLabel603: TppLabel;
    ppLabel604: TppLabel;
    ppUnit12: TppLabel;
    ppRepDate12: TppLabel;
    ppLabel607: TppLabel;
    ppCostCenter12: TppLabel;
    ppLabel609: TppLabel;
    ppLabel610: TppLabel;
    ppLabel611: TppLabel;
    ppEmp12: TppLabel;
    ppLabel613: TppLabel;
    ppLabel614: TppLabel;
    ppSystemVariable23: TppSystemVariable;
    ppLabel615: TppLabel;
    ppSystemVariable24: TppSystemVariable;
    ppHeaderBand12: TppHeaderBand;
    ppShape12: TppShape;
    ppLabel616: TppLabel;
    ppLabel617: TppLabel;
    ppLabel618: TppLabel;
    ppLabel619: TppLabel;
    ppLine361: TppLine;
    ppLine362: TppLine;
    ppLine363: TppLine;
    ppLine364: TppLine;
    ppLine365: TppLine;
    ppLine366: TppLine;
    ppLine367: TppLine;
    ppLabel620: TppLabel;
    ppLabel621: TppLabel;
    ppLabel622: TppLabel;
    ppLine368: TppLine;
    ppLabel623: TppLabel;
    ppLine369: TppLine;
    ppLabel624: TppLabel;
    ppLabel625: TppLabel;
    ppLabel626: TppLabel;
    ppLabel627: TppLabel;
    ppLabel628: TppLabel;
    ppLine370: TppLine;
    ppLine371: TppLine;
    ppLine372: TppLine;
    ppLine373: TppLine;
    ppLine374: TppLine;
    ppLine375: TppLine;
    ppLabel629: TppLabel;
    ppLabel630: TppLabel;
    ppLine376: TppLine;
    ppLine377: TppLine;
    ppLine378: TppLine;
    ppLabel631: TppLabel;
    ppLabel632: TppLabel;
    ppDetailBand12: TppDetailBand;
    ppLine379: TppLine;
    ppLine380: TppLine;
    ppLine381: TppLine;
    ppLine382: TppLine;
    ppLine383: TppLine;
    ppLine384: TppLine;
    ppDBText149: TppDBText;
    ppRow12: TppDBText;
    ppDBText151: TppDBText;
    ppDBText152: TppDBText;
    ppDBText153: TppDBText;
    ppLine385: TppLine;
    ppLine386: TppLine;
    ppLine387: TppLine;
    ppDBText154: TppDBText;
    ppLine388: TppLine;
    ppLine389: TppLine;
    ppLine390: TppLine;
    ppLine391: TppLine;
    ppLine392: TppLine;
    ppDBText155: TppDBText;
    ppDBText156: TppDBText;
    ppDBText157: TppDBText;
    ppDBText158: TppDBText;
    ppDBText159: TppDBText;
    ppDBText160: TppDBText;
    ppDBText161: TppDBText;
    ppLine393: TppLine;
    ppDBText162: TppDBText;
    ppLine394: TppLine;
    ppFooterBand12: TppFooterBand;
    ppLabel633: TppLabel;
    ppLabel634: TppLabel;
    ppLabel635: TppLabel;
    ppLabel636: TppLabel;
    ppLabel637: TppLabel;
    ppLabel638: TppLabel;
    ppLabel639: TppLabel;
    ppLabel640: TppLabel;
    ppLabel641: TppLabel;
    ppLabel642: TppLabel;
    ppLabel643: TppLabel;
    ppLabel644: TppLabel;
    ppLabel645: TppLabel;
    ppLabel646: TppLabel;
    ppLabel647: TppLabel;
    ppLabel648: TppLabel;
    ppLabel649: TppLabel;
    ppLabel650: TppLabel;
    ppLabel651: TppLabel;
    ppLabel652: TppLabel;
    ppLabel653: TppLabel;
    ppLabel654: TppLabel;
    ppLabel655: TppLabel;
    ppLabel656: TppLabel;
    ppDBPipeline12: TppDBPipeline;
    ppField184: TppField;
    ppField185: TppField;
    ppField186: TppField;
    ppField187: TppField;
    ppField188: TppField;
    ppField189: TppField;
    ppField190: TppField;
    ppField191: TppField;
    ppField192: TppField;
    ppField193: TppField;
    ppField194: TppField;
    ppField195: TppField;
    ppField196: TppField;
    ppField197: TppField;
    ppField198: TppField;
    ppField199: TppField;
    ppField200: TppField;
    ppField201: TppField;
    ppField202: TppField;
    dsSpecAnimal: TDataSource;
    ppReport13: TppReport;
    ppTitleBand13: TppTitleBand;
    ppLabel657: TppLabel;
    ppLabel658: TppLabel;
    ppLabel659: TppLabel;
    ppLabel660: TppLabel;
    ppUnit13: TppLabel;
    ppRepDate13: TppLabel;
    ppLabel663: TppLabel;
    ppCostCenter13: TppLabel;
    ppLabel665: TppLabel;
    ppLabel666: TppLabel;
    ppLabel667: TppLabel;
    ppSystemVariable25: TppSystemVariable;
    ppLabel668: TppLabel;
    ppEmp13: TppLabel;
    ppLabel670: TppLabel;
    ppHeaderBand13: TppHeaderBand;
    ppShape13: TppShape;
    ppLabel671: TppLabel;
    ppLabel672: TppLabel;
    ppLabel673: TppLabel;
    ppLabel674: TppLabel;
    ppLine395: TppLine;
    ppLine396: TppLine;
    ppLine397: TppLine;
    ppLine398: TppLine;
    ppLine399: TppLine;
    ppLine400: TppLine;
    ppLine401: TppLine;
    ppLabel675: TppLabel;
    ppLabel676: TppLabel;
    ppLine402: TppLine;
    ppLabel677: TppLabel;
    ppLine403: TppLine;
    ppLabel678: TppLabel;
    ppLabel679: TppLabel;
    ppLabel680: TppLabel;
    ppLabel681: TppLabel;
    ppLabel682: TppLabel;
    ppLine404: TppLine;
    ppLine405: TppLine;
    ppLine406: TppLine;
    ppLine407: TppLine;
    ppLine408: TppLine;
    ppLine409: TppLine;
    ppLabel683: TppLabel;
    ppLabel684: TppLabel;
    ppLine410: TppLine;
    ppLine411: TppLine;
    ppLabel685: TppLabel;
    ppLabel686: TppLabel;
    ppDetailBand13: TppDetailBand;
    ppLine412: TppLine;
    ppLine413: TppLine;
    ppLine414: TppLine;
    ppLine415: TppLine;
    ppLine416: TppLine;
    ppLine417: TppLine;
    ppDBText163: TppDBText;
    ppRow13: TppDBText;
    ppDBText165: TppDBText;
    ppDBText166: TppDBText;
    ppDBText167: TppDBText;
    ppLine418: TppLine;
    ppLine419: TppLine;
    ppLine420: TppLine;
    ppDBText168: TppDBText;
    ppLine421: TppLine;
    ppLine422: TppLine;
    ppLine423: TppLine;
    ppLine424: TppLine;
    ppLine425: TppLine;
    ppDBText169: TppDBText;
    ppDBText170: TppDBText;
    ppDBText171: TppDBText;
    ppDBText172: TppDBText;
    ppDBText173: TppDBText;
    ppDBText174: TppDBText;
    ppDBText175: TppDBText;
    ppLine426: TppLine;
    ppFooterBand13: TppFooterBand;
    ppLabel687: TppLabel;
    ppLabel688: TppLabel;
    ppLabel689: TppLabel;
    ppLabel690: TppLabel;
    ppLabel691: TppLabel;
    ppLabel692: TppLabel;
    ppLabel693: TppLabel;
    ppLabel694: TppLabel;
    ppLabel695: TppLabel;
    ppLabel696: TppLabel;
    ppLabel697: TppLabel;
    ppLabel698: TppLabel;
    ppLabel699: TppLabel;
    ppLabel700: TppLabel;
    ppLabel701: TppLabel;
    ppLabel702: TppLabel;
    ppLabel703: TppLabel;
    ppLabel704: TppLabel;
    ppLabel705: TppLabel;
    ppLabel706: TppLabel;
    ppLabel707: TppLabel;
    ppLabel708: TppLabel;
    ppLabel709: TppLabel;
    ppLabel710: TppLabel;
    ppDBPipeline13: TppDBPipeline;
    ppField203: TppField;
    ppField204: TppField;
    ppField205: TppField;
    ppField206: TppField;
    ppField207: TppField;
    ppField208: TppField;
    ppField209: TppField;
    ppField210: TppField;
    ppField211: TppField;
    ppField212: TppField;
    ppField213: TppField;
    ppField214: TppField;
    ppField215: TppField;
    ppField216: TppField;
    ppField217: TppField;
    ppField218: TppField;
    ppField219: TppField;
    ppField220: TppField;
    ppField221: TppField;
    ppField222: TppField;
    dsSpecIncon: TDataSource;
    cbClass: TRSqlDbLookup;
    spSpecantique: TADOStoredProc;
    spSpecantiqueItem_Code: TStringField;
    spSpecantiqueRec_no: TIntegerField;
    spSpecantiqueItem_Name: TStringField;
    spSpecantiqueLabel: TIntegerField;
    spSpecantiqueCreate_Date: TStringField;
    spSpecantiquebPrice: TFloatField;
    spSpecantiqueGoods_Code: TStringField;
    spSpecantiqueePrice: TFloatField;
    spSpecantiqueUt_code: TSmallintField;
    spSpecantiqueUt_Name: TStringField;
    spSpecantiqueFLName: TStringField;
    spSpecantiqueItem_Desc: TStringField;
    spSpecantiquegoods_codeStr: TStringField;
    spSpecantiqueState_Name: TStringField;
    spSpecantiqueAnt_gcode: TStringField;
    spSpecantiqueAnt_Hprd: TStringField;
    spSpecantiqueAnt_dloc: TStringField;
    spSpecantiqueAnt_ddate: TStringField;
    spSpecantiqueAnt_weight: TStringField;
    spSpecantiqueAnt_color: TStringField;
    spSpecantiqueAnt_dim: TStringField;
    spSpecantiqueAnt_mark: TStringField;
    spSpecantiqueAnt_Pdate: TStringField;
    spSpecantiqueAnt_desc: TStringField;
    spSpecMuseum: TADOStoredProc;
    spSpecStamp: TADOStoredProc;
    spSpecRide: TADOStoredProc;
    spSpecLab: TADOStoredProc;
    spSpecMachinery: TADOStoredProc;
    spSpecBooks: TADOStoredProc;
    spSpecLens: TADOStoredProc;
    spSpecTextile: TADOStoredProc;
    spSpecDiskette: TADOStoredProc;
    spSpecTaxidermy: TADOStoredProc;
    spSpecAnimal: TADOStoredProc;
    spSpecIncon: TADOStoredProc;
    spSpecMuseumFLName: TStringField;
    spSpecMuseumItem_name: TStringField;
    spSpecMuseumRec_no: TIntegerField;
    spSpecMuseumDate: TStringField;
    spSpecMuseumbPrice: TFloatField;
    spSpecMuseumEPrice: TFloatField;
    spSpecMuseumMts_gcode: TStringField;
    spSpecMuseumMts_type: TSmallintField;
    spSpecMuseumMts_loc: TStringField;
    spSpecMuseumMts_style: TStringField;
    spSpecMuseumMts_rag: TStringField;
    spSpecMuseumMts_mat: TStringField;
    spSpecMuseumMts_woof: TStringField;
    spSpecMuseumMts_fuzz: TStringField;
    spSpecMuseumMts_plane: TStringField;
    spSpecMuseumMts_bcolor: TStringField;
    spSpecMuseumMts_color: TStringField;
    spSpecMuseumMts_len: TStringField;
    spSpecMuseumMts_with: TStringField;
    spSpecMuseumMts_area: TStringField;
    spSpecMuseumMts_date: TStringField;
    spSpecMuseumMts_frame: TStringField;
    spSpecMuseumMts_old: TStringField;
    spSpecMuseumMts_degree: TStringField;
    spSpecMuseumMts_pdate: TStringField;
    spSpecMuseumMyGoodCode: TStringField;
    spSpecMuseumEmp: TStringField;
    spSpecMuseumgoods_codeStr: TStringField;
    spSpecMuseumtypecase: TStringField;
    spSpecMuseumState_Name: TStringField;
    spSpecStampFLName: TStringField;
    spSpecStampItem_name: TStringField;
    spSpecStampRec_no: TIntegerField;
    spSpecStampDate: TStringField;
    spSpecStampbPrice: TFloatField;
    spSpecStampEPrice: TFloatField;
    spSpecStampSts_gcode: TStringField;
    spSpecStampSts_Type: TSmallintField;
    spSpecStampSts_price: TFloatField;
    spSpecStampSts_len: TSmallintField;
    spSpecStampSts_wit: TSmallintField;
    spSpecStampSts_isue: TStringField;
    spSpecStampSts_design: TStringField;
    spSpecStampSts_date: TStringField;
    spSpecStampSts_qul: TSmallintField;
    spSpecStampSts_ptype: TStringField;
    spSpecStampSts_perf: TSmallintField;
    spSpecStampSts_back: TSmallintField;
    spSpecStampSts_face: TSmallintField;
    spSpecStampSts_desc: TStringField;
    spSpecStampMyGoodCode: TStringField;
    spSpecStampEmp: TStringField;
    spSpecStampgoods_codeStr: TStringField;
    spSpecStampqulcase: TStringField;
    spSpecStamppercase: TStringField;
    spSpecStampbackcase: TStringField;
    spSpecStampfacecase: TStringField;
    spSpecStamptypecase: TStringField;
    spSpecStampState_Name: TStringField;
    spSpecRideFLName: TStringField;
    spSpecRideItem_name: TStringField;
    spSpecRideRec_no: TIntegerField;
    spSpecRideDate: TStringField;
    spSpecRidebPrice: TFloatField;
    spSpecRideEPrice: TFloatField;
    spSpecRideTra_gcode: TStringField;
    spSpecRideTra_type: TSmallintField;
    spSpecRideTra_mcou: TStringField;
    spSpecRideTra_mfac: TStringField;
    spSpecRideTra_eno: TStringField;
    spSpecRideTra_cno: TStringField;
    spSpecRideTra_pno: TStringField;
    spSpecRideTra_color: TStringField;
    spSpecRideTra_mod: TStringField;
    spSpecRideTra_cap: TStringField;
    spSpecRideTra_mdate: TStringField;
    spSpecRideTra_desc: TStringField;
    spSpecRideMyGoodCode: TStringField;
    spSpecRideEmp: TStringField;
    spSpecRidegoods_codeStr: TStringField;
    spSpecRideTypeName: TStringField;
    spSpecRideState_Name: TStringField;
    spSpecLabFLName: TStringField;
    spSpecLabItem_name: TStringField;
    spSpecLabRec_no: TIntegerField;
    spSpecLabDate: TStringField;
    spSpecLabbPrice: TFloatField;
    spSpecLabEPrice: TFloatField;
    spSpecLabgoods_code: TStringField;
    spSpecLabmaker_country: TStringField;
    spSpecLabmaker_factory: TStringField;
    spSpecLabfactory_no: TStringField;
    spSpecLabmodel: TStringField;
    spSpecLabserial: TStringField;
    spSpecLabspecification: TStringField;
    spSpecLabMyGoodCode: TStringField;
    spSpecLabEmp: TStringField;
    spSpecLabgoods_codeStr: TStringField;
    spSpecLabState_Name: TStringField;
    spSpecMachineryFLName: TStringField;
    spSpecMachineryItem_name: TStringField;
    spSpecMachineryRec_no: TIntegerField;
    spSpecMachineryDate: TStringField;
    spSpecMachinerybPrice: TFloatField;
    spSpecMachineryEPrice: TFloatField;
    spSpecMachinerygoods_code: TStringField;
    spSpecMachinerymaker_country: TStringField;
    spSpecMachinerymaker_factory: TStringField;
    spSpecMachineryfactory_no: TStringField;
    spSpecMachineryengine_no: TStringField;
    spSpecMachinerymodel: TStringField;
    spSpecMachinerycapacity: TStringField;
    spSpecMachineryserial: TStringField;
    spSpecMachinerymake_date: TStringField;
    spSpecMachineryspecification: TStringField;
    spSpecMachineryMyGoodCode: TStringField;
    spSpecMachineryEmp: TStringField;
    spSpecMachinerygoods_codeStr: TStringField;
    spSpecMachineryState_Name: TStringField;
    spSpecBooksFLName: TStringField;
    spSpecBooksItem_name: TStringField;
    spSpecBooksRec_no: TIntegerField;
    spSpecBooksDate: TStringField;
    spSpecBooksbPrice: TFloatField;
    spSpecBooksEPrice: TFloatField;
    spSpecBooksbos_gcode: TStringField;
    spSpecBooksbos_name: TStringField;
    spSpecBooksbos_aut: TStringField;
    spSpecBooksbos_date: TStringField;
    spSpecBooksbos_trans: TStringField;
    spSpecBooksbos_publ: TStringField;
    spSpecBooksbos_num: TIntegerField;
    spSpecBooksbos_dim: TStringField;
    spSpecBooksbos_ptype: TStringField;
    spSpecBooksbos_ctype: TSmallintField;
    spSpecBooksbos_chtype: TSmallintField;
    spSpecBooksbos_cname: TStringField;
    spSpecBooksbos_desc: TStringField;
    spSpecBooksMyGoodCode: TStringField;
    spSpecBooksEmp: TStringField;
    spSpecBooksgoods_codeStr: TStringField;
    spSpecBooksbos_cTypeName: TStringField;
    spSpecBooksbos_chTypeName: TStringField;
    spSpecBooksState_Name: TStringField;
    spSpecTextileFLName: TStringField;
    spSpecTextileItem_name: TStringField;
    spSpecTextileRec_no: TIntegerField;
    spSpecTextileDate: TStringField;
    spSpecTextilebPrice: TFloatField;
    spSpecTextileEPrice: TFloatField;
    spSpecTextilegoods_code: TStringField;
    spSpecTextiletexture_type: TSmallintField;
    spSpecTextiletexture_loc: TStringField;
    spSpecTextilemark: TStringField;
    spSpecTextiletexture_date: TStringField;
    spSpecTextilelength: TStringField;
    spSpecTextilewidth: TStringField;
    spSpecTextileback_color: TStringField;
    spSpecTextileborder_color: TStringField;
    spSpecTextilespecification: TStringField;
    spSpecTextilemap: TStringField;
    spSpecTextileMyGoodCode: TStringField;
    spSpecTextileEmp: TStringField;
    spSpecTextilegoods_codeStr: TStringField;
    spSpecTextiletypecase: TStringField;
    spSpecTextileState_Name: TStringField;
    spSpecDisketteFLName: TStringField;
    spSpecDisketteItem_name: TStringField;
    spSpecDisketteRec_no: TIntegerField;
    spSpecDisketteDate: TStringField;
    spSpecDiskettebPrice: TFloatField;
    spSpecDisketteEPrice: TFloatField;
    spSpecDiskettegoods_code: TStringField;
    spSpecDiskettesubject: TStringField;
    spSpecDiskettetype: TSmallintField;
    spSpecDiskettegood_size: TStringField;
    spSpecDiskettesize_unit: TSmallintField;
    spSpecDiskettemeasure_unit: TSmallintField;
    spSpecDiskettespecification: TStringField;
    spSpecDisketteMyGoodCode: TStringField;
    spSpecDisketteEmp: TStringField;
    spSpecDiskettegoods_codeStr: TStringField;
    spSpecDiskettetypecase: TStringField;
    spSpecDiskettesizecase: TStringField;
    spSpecDiskettemecase: TStringField;
    spSpecDisketteState_Name: TStringField;
    spSpecAnimalFLName: TStringField;
    spSpecAnimalItem_name: TStringField;
    spSpecAnimalRec_no: TIntegerField;
    spSpecAnimalDate: TStringField;
    spSpecAnimalbPrice: TFloatField;
    spSpecAnimalEPrice: TFloatField;
    spSpecAnimalGoods_code: TStringField;
    spSpecAnimalsex: TSmallintField;
    spSpecAnimalorigin: TStringField;
    spSpecAnimalspecial_mark: TStringField;
    spSpecAnimalcolor: TStringField;
    spSpecAnimalheight: TSmallintField;
    spSpecAnimalage: TSmallintField;
    spSpecAnimalspecification: TStringField;
    spSpecAnimalMyGoodCode: TStringField;
    spSpecAnimalEmp: TStringField;
    spSpecAnimalgoods_codeStr: TStringField;
    spSpecAnimalsexcase: TStringField;
    spSpecAnimalState_Name: TStringField;
    spSpecTaxidermyFLName: TStringField;
    spSpecTaxidermyItem_name: TStringField;
    spSpecTaxidermyRec_no: TIntegerField;
    spSpecTaxidermyDate: TStringField;
    spSpecTaxidermybPrice: TFloatField;
    spSpecTaxidermyEPrice: TFloatField;
    spSpecTaxidermygoods_code: TStringField;
    spSpecTaxidermytype: TStringField;
    spSpecTaxidermyskeleton: TStringField;
    spSpecTaxidermyexternal_case: TStringField;
    spSpecTaxidermyfossil: TStringField;
    spSpecTaxidermycollect_loc: TStringField;
    spSpecTaxidermyspecification: TStringField;
    spSpecTaxidermyMyGoodCode: TStringField;
    spSpecTaxidermyEmp: TStringField;
    spSpecTaxidermygoods_codeStr: TStringField;
    spSpecTaxidermyState_Name: TStringField;
    spSpecInconFLName: TStringField;
    spSpecInconItem_name: TStringField;
    spSpecInconRec_no: TIntegerField;
    spSpecInconDate: TStringField;
    spSpecInconbPrice: TFloatField;
    spSpecInconEPrice: TFloatField;
    spSpecIncongoods_code: TStringField;
    spSpecInconmaker_country: TStringField;
    spSpecInconmaker_unit: TStringField;
    spSpecInconweight: TIntegerField;
    spSpecIncondimension: TStringField;
    spSpecInconcolor: TStringField;
    spSpecInconmodel: TStringField;
    spSpecInconserial: TStringField;
    spSpecInconampere: TStringField;
    spSpecInconspecification: TStringField;
    spSpecInconMyGoodCode: TStringField;
    spSpecInconEmp: TStringField;
    spSpecIncongoods_codeStr: TStringField;
    spSpecInconState_Name: TStringField;
    procedure FormClose(Sender: TObject; var Action: TCloseAction);
    procedure FormActivate(Sender: TObject);
    procedure FormDeactivate(Sender: TObject);

    procedure spbPreview100PercentClick(Sender: TObject);
    procedure spbPreviewWidthClick(Sender: TObject);
    procedure spbPreviewWholeClick(Sender: TObject);
    procedure mskPreviewPageKeyPress(Sender: TObject; var Key: Char);
    procedure spbPreviewNextClick(Sender: TObject);
    procedure spbPreviewPriorClick(Sender: TObject);
    procedure mskPreviewPercentageKeyPress(Sender: TObject; var Key: Char);
    procedure quFunFormalRowGetText(Sender: TField; var Text: String;
      DisplayText: Boolean);
    procedure FormShow(Sender: TObject);
    procedure dblUnitCloseUp(Sender: TObject);
    procedure dblCostCenterCloseUp(Sender: TObject);
    procedure dblCostCenterEnter(Sender: TObject);
    procedure dblLocCodeEnter(Sender: TObject);
    procedure ppRow1GetText(Sender: TObject; var Text: String);
    procedure ppUnit1GetText(Sender: TObject; var Text: String);
    procedure ppCostCenter1GetText(Sender: TObject; var Text: String);
    procedure ppLocCode1GetText(Sender: TObject; var Text: String);
    procedure ppEmp1GetText(Sender: TObject; var Text: String);
    procedure ppRepDate1GetText(Sender: TObject; var Text: String);

  private

    //procedure MakeQuery;

    { Private declarations }
  public
    res:integer;
    amt:integer;
    fin:integer;
    Prog_Code : Integer ;
    Prog_Sal : Smallint ;

  protected
    procedure DoRun(var mes :TMessage);message RUN_CMD;
    procedure DoPrint(var mes :TMessage);message F_PRINT;
    { Public declarations }
  end;

var
  reSpecAll: TreSpecAll;
  ActiveQuery:TADOStoredProc;
  i : integer;
implementation

uses UCommon;



{$R *.DFM}


procedure TreSpecAll.DoRun(var mes :TMessage);
begin
    if(cbClass.KeyValue=Null) then
    begin
      DabData.ShowPopupMessage('«» œ« ÿ»ﬁÂ „Ê—œ ‰Ÿ— —« «‰ Œ«» ‰„«ÌÌœ');
      exit;
    end;
// if ((dblUnit.text<>'') and (dblCostCenter.text<>'') and (dblLocCode.text<>'') ) then
   begin
     i := 0;
     Case (cbClass.KeyValue) of
       1:
       begin
          ActiveQuery:=spSpecantique;
          ppViewer1.Report:=ppReport1;
       end;
       2:
       begin
          ActiveQuery:=spSpecMuseum;
          ppViewer1.Report:=ppReport2;
       end;
       3:
       begin
          ActiveQuery:=spSpecStamp;
          ppViewer1.Report:=ppReport3;
       end;
       4:
       begin
          ActiveQuery:=spSpecRide;
          ppViewer1.Report:=ppReport4;
       end;
       5:
       begin
          ActiveQuery:=spSpecLab;
          ppViewer1.Report:=ppReport5;
       end;
       6:
       begin
          ActiveQuery:=spSpecMachinery;
          ppViewer1.Report:=ppReport6;
       end;
       7:
       begin
          ActiveQuery:=spSpecBooks;
          ppViewer1.Report:=ppReport7;
       end;
       8:
       begin
          ActiveQuery:=spSpecLens;
          ppViewer1.Report:=ppReport8;
       end;
       9:
       begin
          ActiveQuery:=spSpecTextile;
          ppViewer1.Report:=ppReport9;
       end;
       10:
       begin
          ActiveQuery:=spSpecDiskette;
          ppViewer1.Report:=ppReport10;
       end;
       11:
       begin
          ActiveQuery:=spSpecTaxidermy;
          ppViewer1.Report:=ppReport11;
       end;
       12:
       begin
          ActiveQuery:=spSpecAnimal;
          ppViewer1.Report:=ppReport12;
       end;
       13:
       begin
          ActiveQuery:=spSpecIncon;
          ppViewer1.Report:=ppReport13;
       end;
       else
       begin
         DabData.ShowPopupMessage('«» œ« ÿ»ﬁÂ „Ê—œ ‰Ÿ— —« «‰ Œ«» ‰„«ÌÌœ');
         exit;
       end;
     end;
     ActiveQuery.close;
     if trim(dblunit.text)<>'' then
           ActiveQuery.Parameters[1].value := dblUnit.KeyValue
     else ActiveQuery.Parameters[1].value :=null;
     if trim(dblCostCenter.text)<>'' then
       ActiveQuery.Parameters[2].value := dblCostCenter.KeyValue
     else ActiveQuery.Parameters[2].value :=null;
     if trim(dblLocCode.text)<>'' then
        ActiveQuery.Parameters[3].value := dblLocCode.KeyValue
     else ActiveQuery.Parameters[3].value :=null;
     if trim(dblemp.text)<>'' then
        ActiveQuery.Parameters[4].value := dblemp.KeyValue
     else ActiveQuery.Parameters[4].value :=null;

     ActiveQuery.open;

     ppViewer1.reset;
     ppViewer1.Report.PrintToDevices;
  end;
   end;


procedure TreSpecAll.DoPrint(var mes :TMessage);
begin
  ppViewer1.Print;
end;

procedure TreSpecAll.FormClose(Sender: TObject; var Action: TCloseAction);
begin
 FormDeactivate(nil);
{ recredit:=nil;}
 Action:=CaFree;
end;

procedure TreSpecAll.FormActivate(Sender: TObject);
var mes:TMessage;
begin
   mes.Msg := FORM_STATE;
   mes.Lparam := 45;
   Application.MainForm.Dispatch(mes);
   Left := 0;
   Top := 0;
end;


procedure TreSpecAll.FormDeactivate(Sender: TObject);
var mes:TMessage;
begin
 mes.Msg:=FORM_DEACT;
 Application.MainForm.Dispatch(mes);
end;

procedure TreSpecAll.spbPreview100PercentClick(Sender: TObject);
begin
  ppViewer1.ZoomSetting := zs100Percent;
  mskPreviewPercentage.Text := IntToStr(ppViewer1.CalculatedZoom);
  panel2.SetFocus;
end;



procedure TreSpecAll.spbPreviewWidthClick(Sender: TObject);
begin
  ppViewer1.ZoomSetting := zsPageWidth;
  mskPreviewPercentage.Text := IntToStr(ppViewer1.CalculatedZoom);
end;



procedure TreSpecAll.spbPreviewWholeClick(Sender: TObject);
begin
  ppViewer1.ZoomSetting := zsWholePage;
  mskPreviewPercentage.Text := IntToStr(ppViewer1.CalculatedZoom);
end;



procedure TreSpecAll.mskPreviewPageKeyPress(Sender: TObject; var Key: Char);
var
  liPage: Longint;
begin

  if (Key = #13) then
    begin
      liPage := StrToInt(mskPreviewPage.Text);
      ppViewer1.GotoPage(liPage);
    end;
end;

procedure TreSpecAll.spbPreviewNextClick(Sender: TObject);
begin
  ppViewer1.NextPage;
  mskPreviewPage.text:=inttostr(ppViewer1.AbsolutePageNo);
end;

procedure TreSpecAll.spbPreviewPriorClick(Sender: TObject);
begin
  ppViewer1.PriorPage;
  mskPreviewPage.text:=inttostr(ppViewer1.AbsolutePageNo);
end;

procedure TreSpecAll.mskPreviewPercentageKeyPress(Sender: TObject;
  var Key: Char);
var
  liPercentage: Integer;
begin
  if (Key = #13) then
    begin
      liPercentage := StrToIntDef(mskPreviewPercentage.Text, 100);

      ppViewer1.ZoomPercentage := liPercentage;

      spbPreviewWhole.Down := False;
      spbPreviewWidth.Down := False;
      spbPreview100Percent.Down := False;

      mskPreviewPercentage.Text := IntToStr(ppViewer1.CalculatedZoom);
    end; {if, carriage return pressed}

end; {procedure, mskPreviewPercentageKeyPress}

procedure TreSpecAll.quFunFormalRowGetText(Sender: TField;
  var Text: String; DisplayText: Boolean);
var F :Tfield;
begin
   Text:='';
   f := Sender;
   if f.DataSet = nil then exit;
   if not f.DataSet.Active then exit;
   if f.DataSet.RecNo < 1 then exit;
   Text := inttostr(f.DataSet.RecNo);
end;


procedure TreSpecAll.FormShow(Sender: TObject);
begin

   DabData.quOrgUnit.Close;
   DabData.quOrgUnit.Parameters[0].Value := OrganizCode;
   DabData.quOrgUnit.Open;

   DabData.quemp.Close;
   DabData.quemp.open;
   DabData.quClass.Close;
   DabData.quClass.Parameters[0].Value:=2;
   DabData.quClass.open;
   ppViewer1.reset;
end;

procedure TreSpecAll.dblUnitCloseUp(Sender: TObject);
begin
   DabData.quCostCenter.Close;
   DabData.quCostCenter.Parameters[0].Value := OrganizCode;
   DabData.quCostCenter.Parameters[1].Value := DabData.quOrgUnitUt_Code.AsInteger;
   DabData.quCostCenter.Open;
   dblCostCenter.KeyValue := -1 ;

   DabData.quDeployLoc.Close;
   DabData.quDeployLoc.Parameters[0].Value := 0;
   DabData.quDeployLoc.Parameters[1].Value := 0;
   DabData.quDeployLoc.Open;
   dblLocCode.KeyValue := -1 ;
end;

procedure TreSpecAll.dblCostCenterCloseUp(Sender: TObject);
begin
      DabData.quDeployLoc.Close;
      DabData.quDeployLoc.Parameters[0].Value := OrganizCode;
      DabData.quDeployLoc.Parameters[1].Value := DabData.quCostCenterUt_Code.AsInteger;
      DabData.quDeployLoc.Open;
      dblLocCode.KeyValue := -1 ;
end;

procedure TreSpecAll.dblCostCenterEnter(Sender: TObject);
begin
   if not(CheckNull(dblUnit.Text)) then
   begin
      DabData.quCostCenter.Close;
      DabData.quCostCenter.Parameters[0].Value := 0;
      DabData.quCostCenter.Parameters[1].Value := 0;
      DabData.quCostCenter.Open;
      dblCostCenter.KeyValue := -1 ;
   end
   else
   if (CheckNull(dblUnit.Text)) then
   begin
      DabData.quCostCenter.Close;
      DabData.quCostCenter.Parameters[0].Value := OrganizCode;
      DabData.quCostCenter.Parameters[1].Value := dblUnit.KeyValue;
      DabData.quCostCenter.Open;
      dblCostCenter.KeyValue := -1 ;
   end
end;

procedure TreSpecAll.dblLocCodeEnter(Sender: TObject);
begin
   if not(CheckNull(dblCostCenter.Text) ) then
   begin
      DabData.quDeployLoc.Close;
      DabData.quDeployLoc.Parameters[0].Value := 0;
      DabData.quDeployLoc.Parameters[1].Value := 0;
      DabData.quDeployLoc.Open;
      dblLocCode.KeyValue := -1 ;
   end;
end;

procedure TreSpecAll.ppRow1GetText(Sender: TObject; var Text: String);
begin
  inherited;
  inc(i);
  Text:=IntToStr(i div 3);
end;

procedure TreSpecAll.ppUnit1GetText(Sender: TObject; var Text: String);
begin
  inherited;
  Text:=dblUnit.text;
end;

procedure TreSpecAll.ppCostCenter1GetText(Sender: TObject;
  var Text: String);
begin
  inherited;
  Text:=dblCostCenter.Text;
end;

procedure TreSpecAll.ppLocCode1GetText(Sender: TObject; var Text: String);
begin
  inherited;
  Text:=dblLocCode.Text;
end;

procedure TreSpecAll.ppEmp1GetText(Sender: TObject; var Text: String);
begin
  inherited;
  Text:=dblEmp.Text;
end;

procedure TreSpecAll.ppRepDate1GetText(Sender: TObject; var Text: String);
begin
  inherited;
  Text:=Dabdata.disp_date;
end;

end.
